import * as mongoose from 'mongoose';
import * as dotenv from 'dotenv';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/portfolio';

// Schema Definition (simplified for seeding)
const SkillItemSchema = new mongoose.Schema({
    name: String,
    level: String,
    icon: String,
    description: String,
});

const SkillCategorySchema = new mongoose.Schema({
    title: String,
    items: [SkillItemSchema],
});

const SkillCategoryModel = mongoose.model('SkillCategory', SkillCategorySchema);

// Data to Seed
const SKILL_DATA = [
    {
        title: "Frontend",
        items: [
            {
                name: "React",
                level: "Expert",
                icon: "SiReact",
                description: `Built scalable, component-driven UIs with Suspense data fetching, hooks, accessibility (a11y), and performance tuning.

### Highlights
* Reusable UI patterns: cards, modals, skeletons, media banners
* Client/Server Components composition with clean boundaries

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "Next.js",
                level: "Expert",
                icon: "SiNextdotjs",
                description: `App Router, Server Actions, image optimization, route groups, and Suspense for streaming UI.

### Highlights
* Built responsive hero with trailer overlay and modal details
* Handled env-based API URLs and build-time optimizations

### Applied In
* Nextflix`
            },
            {
                name: "TailwindCSS",
                level: "Expert",
                icon: "SiTailwindcss",
                description: `Utility-first styling, responsive grids, design tokens, and dark-friendly surfaces.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "shadcn/ui",
                level: "Advanced",
                icon: "SiShadcnui",
                description: `Accessible primitives with consistent theming for production-ready components.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "Framer Motion",
                level: "Intermediate",
                icon: "SiFramer",
                description: `Micro-interactions and carousel transitions for smoother UX.

### Applied In
* Nextflix`
            }
        ]
    },
    {
        title: "Backend",
        items: [
            {
                name: "Node.js",
                level: "Advanced",
                icon: "SiNodedotjs",
                description: `API runtime with environment-driven config and Dockerized workflows.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "NestJS",
                level: "Advanced",
                icon: "SiNestjs",
                description: `Modular API with versioned routes, providers, and clean layering.

### Highlights
* Movies module with service/use-cases and TMDb client
* Global validation pipes and URI versioning (/api/v1)

### Applied In
* Nextflix`
            },
            {
                name: "Express",
                level: "Advanced",
                icon: "SiExpress",
                description: `Routing, controllers, auth middleware, and error handling for REST APIs.

### Applied In
* HugPaw`
            },
            {
                name: "Swagger/OpenAPI",
                level: "Intermediate",
                icon: "SiSwagger",
                description: `Autogenerated API docs for faster iteration and testing at /docs.

### Applied In
* Nextflix`
            }
        ]
    },
    {
        title: "Database",
        items: [
            {
                name: "MongoDB",
                level: "Advanced",
                icon: "SiMongodb",
                description: `Schema-based models (Mongoose), lean queries, and aggregations.

### Applied In
* HugPaw`
            },
            {
                name: "PostgreSQL",
                level: "Intermediate",
                icon: "SiPostgresql",
                description: `Relational modeling and analytics use-cases (separate data eng work).`
            }
        ]
    },
    {
        title: "DevOps",
        items: [
            {
                name: "Git",
                level: "Advanced",
                icon: "SiGit",
                description: `Branching, PR reviews, semantic commits, and release tagging.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "GitHub",
                level: "Advanced",
                icon: "SiGithub",
                description: `Issues/Projects, code reviews, and basic CI/CD pipelines.

[GitHub profile](https://github.com/Izenberk)`
            },
            {
                name: "pnpm",
                level: "Advanced",
                icon: "SiPnpm",
                description: `Fast, disk-efficient package management across workspaces/monorepo.

### Applied In
* Nextflix`
            },
            {
                name: "Docker",
                level: "Intermediate",
                icon: "SiDocker",
                description: `Multi-stage builds and reproducible dev/prod environments.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "Vercel",
                level: "Intermediate",
                icon: "SiVercel",
                description: `Deployed frontend with preview builds and environment management.

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "Render",
                level: "Intermediate",
                icon: "SiRender",
                description: `Deployed backend APIs with managed SSL and env vars.

### Applied In
* Nextflix
* HugPaw`
            }
        ]
    },
    {
        title: "Languages",
        items: [
            {
                name: "TypeScript",
                level: "Expert",
                icon: "SiTypescript",
                description: `Strongly typed JavaScript for safer, more predictable code. Applied generics, enums, interfaces, and union types for scalable architecture.

### Highlights
* Shared type contracts across monorepo packages
* Strict mode and structural typing ensured API stability

### Applied In
* Nextflix
* HugPaw`
            },
            {
                name: "JavaScript",
                level: "Expert",
                icon: "SiJavascript",
                description: `Core logic layer for all projects, mastering modern ES6+ syntax, async/await, closures, and functional patterns.

### Highlights
* Extensive use of async data fetching, array/object transformations, and error handling
* Deep understanding of event loop and async flow

### Applied In
* Nextflix
* HugPaw`
            }
        ]
    },
    {
        title: "Other",
        items: [
            {
                name: "DSA",
                level: "Advanced",
                icon: "SiLeetcode",
                description: `Focused on core algorithmic problem solving — arrays, trees, graphs, recursion, and complexity analysis.

### Highlights
* Practiced optimized patterns in LeetCode-style challenges
* Improved reasoning and clean-code efficiency through iterative problem solving`
            },
            {
                name: "TMDb",
                level: "Intermediate",
                icon: "SiThemoviedatabase",
                description: `Integrated The Movie Database (TMDb) API for dynamic movie discovery, metadata, and media streaming previews.

### Highlights
* Used paginated endpoints (Now Playing, Popular, Top Rated, Upcoming)
* Mapped image paths and trailers with domain-safe DTOs

### Applied In
* Nextflix`
            }
        ]
    }
];

async function seed() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(MONGO_URI);
        console.log('Connected!');

        console.log('Clearing existing skills...');
        await SkillCategoryModel.deleteMany({});

        console.log('Seeding new skills...');
        await SkillCategoryModel.insertMany(SKILL_DATA);

        console.log('Done! Skills seeded successfully.');
        process.exit(0);
    } catch (error) {
        console.error('Error seeding skills:', error);
        process.exit(1);
    }
}

seed();
